using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace mhxedit
{
    public partial class Form1 : Form
    {
        FileStream _saveFile = null;
        MonHunSave _save = null;
        MonHunCharacter selSlot = null;

        public Form1()
        {
            InitializeComponent();
        }

        private void miFile_Click(object sender, EventArgs e)
        {

        }

        private void openToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var res = openFileDialog1.ShowDialog();
            if (res == DialogResult.OK)
            {
                _save = new MonHunSave(openFileDialog1.FileName);

                // GUI
                toolStripComboBox1.Enabled = true;

            }
        }

        private void openFileDialog1_FileOk(object sender, CancelEventArgs e)
        {

        }

        private void toolStripComboBox1_Click(object sender, EventArgs e)
        {

        }

        private void menuStrip1_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }

        private void Form1_Load(object sender, EventArgs e)
        {
            tabControl1.SelectedIndex = 1;
        }

        private void toolStripComboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            selSlot = _save.slots[toolStripComboBox1.SelectedIndex];

            textBoxName.Text = selSlot.name;
            textBoxPlayTime.Text = selSlot.playTime.ToString();
            textBoxZenny.Text = selSlot.zenny.ToString();
            textBoxRank.Text = selSlot.hr.ToString();


            monHunItemBindingSource.Clear();
            foreach (var item in selSlot.itemBox)
            {
                monHunItemBindingSource.Add(item);
            }
        }

        private void saveToolStripMenuItem_Click(object sender, EventArgs e)
        {
            _save.Save(openFileDialog1.FileName);
            
        }

        private void textBoxName_TextChanged(object sender, EventArgs e)
        {
            selSlot = _save.slots[toolStripComboBox1.SelectedIndex];
            selSlot.name = textBoxName.Text;
        }

        private void dataGridView1_DataError(object sender, DataGridViewDataErrorEventArgs e)
        {
            if (e.Exception != null && ((e.Context & DataGridViewDataErrorContexts.Commit) == DataGridViewDataErrorContexts.Commit))
            {
                switch (e.ColumnIndex)
                {
                    case 0:
                        MessageBox.Show("ID has to be an integer value between 0 and 32767");
                        break;
                    case 1:
                        MessageBox.Show("Count has to be an integer value between 0 and 99");
                        break;
                    default:
                        break;
                }
                
            }
        }

        private void textBoxSearch_TextChanged(object sender, EventArgs e)
        {
            listBoxSearchResults.Items.Clear();
            string search = textBoxSearch.Text.ToLower();
            for (uint i=0; i < MonHunItem.names.Length; i++)
            {
                var item = MonHunItem.names[i];

                if (item.ToLower().Contains(search))
                {
                    listBoxSearchResults.Items.Add(new KeyValuePair<string, uint>(item, i));
                }
            }
        }

        private void buttonSearchOverwrite_Click(object sender, EventArgs e)
        {
            if(dataGridView1.SelectedCells.Count == 0 || listBoxSearchResults.SelectedItem == null)
            {
                return;
            }

            var item = (MonHunItem)(dataGridView1.SelectedCells[0].OwningRow.DataBoundItem);
            item.Count = (uint)(numericUpDown1.Value);
            item.ID = ((KeyValuePair<string, uint>)(listBoxSearchResults.SelectedItem)).Value;
            dataGridView1.InvalidateRow(dataGridView1.SelectedCells[0].OwningRow.Index);
        }

        private void aboutToolStripMenuItem_Click(object sender, EventArgs e)
        {
            AboutBox1 about = new AboutBox1();
            about.ShowDialog();
        }

        private void buttonSetSelMax_Click(object sender, EventArgs e)
        {
            if (dataGridView1.SelectedCells.Count == 0 || listBoxSearchResults.SelectedItem == null)
            {
                return;
            }

            var item = (MonHunItem)(dataGridView1.SelectedCells[0].OwningRow.DataBoundItem);
            item.Count = (uint)(99);
            dataGridView1.InvalidateRow(dataGridView1.SelectedCells[0].OwningRow.Index);
        }

        private void buttonSetAllMax_Click(object sender, EventArgs e)
        {
            foreach (var item in selSlot.itemBox)
            {
                if(item.ID!=0) item.Count = (uint)(99);
            }
            dataGridView1.EndEdit();
            dataGridView1.Refresh();
        }

        private void label8_Click(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            int start = dataGridView1.SelectedCells[0].OwningRow.Index;
            int end = start + (int)(numLoopCount.Value);
            uint amount = (uint)(numItemAmount.Value);
            uint id = (uint)(numStartID.Value);

            for (; start < end; start++, id++)
            {
                selSlot.itemBox[start].ID = id;
                selSlot.itemBox[start].Count = amount;
            }

            dataGridView1.EndEdit();
            dataGridView1.Refresh();
        }
    }


    class MonHunSave
    {
        uint unknown;
        byte slotFirst;
        byte slotSecond;
        byte slotThird;
        byte slotLast;
        uint unknown2;
        uint[] slotOffsets;

        public MonHunCharacter[] slots;

        public MonHunSave(string fileName)
        {
            using (FileStream fs = new FileStream(fileName, FileMode.Open))
            {
                BinaryReader reader = new BinaryReader(fs);

                // Read character slot offsets
                slotOffsets = new uint[3];
                fs.Seek(0x10, SeekOrigin.Begin);
                for (int i = 0; i < 3; i++)
                {
                    slotOffsets[i] = reader.ReadUInt32();
                }

                // read character slots
                MemoryStream[] ms = new MemoryStream[3];
                slots = new MonHunCharacter[3];
                for (int i = 0; i < 3; i++)
                {
                    // Read a character
                    fs.Seek(slotOffsets[i], SeekOrigin.Begin);
                    ms[i] = new MemoryStream(reader.ReadBytes(0xEB52C));
                    slots[i] = new MonHunCharacter(ms[i]);
                }
            }
        }

        public void Save(string fileName)
        {
            using (var file = new FileStream(fileName, FileMode.Open))
            {
                BinaryWriter writer = new BinaryWriter(file);
                for (int i = 0; i < 3; i++)
                {
                    file.Seek(slotOffsets[i], SeekOrigin.Begin);
                    writer.Write(slots[i].SerializeBase());

                    file.Seek(slotOffsets[i] + 0x290, SeekOrigin.Begin);
                    writer.Write(slots[i].SerializeItemBox());
                }
                
            }
        }
    }

    public class MonHunCharacter
    {
        MemoryStream _ms;
        BinaryReader _reader;

        public string name;
        public uint playTime;
        public uint zenny;
        public ushort hr;
        public MonHunItem[] itemBox;


        public byte[] SerializeBase()
        {
            byte[] ret = new byte[42];
            BinaryWriter writer = new BinaryWriter(new MemoryStream(ret));

            byte[] bname = new byte[32];
            for (int i = 0; i < 32; i++) bname[i] = 0;
            System.Text.Encoding.UTF8.GetBytes(name, 0, name.Length, bname, 0);
            writer.Write(bname);
            writer.Write(playTime);
            writer.Write(zenny);
            writer.Write(hr);

            return ret;
        }

        public byte[] SerializeItemBox()
        {
            byte[] ret = new byte[3150];
            BinaryWriter writer = new BinaryWriter(new MemoryStream(ret));

            uint buffer = 0;
            uint bits = 0;
            byte b = 0;
            for (int i = 0; i < 1400; i++)
            {
                buffer = (itemBox[i].GetRaw() << ((int)bits)) | buffer;
                bits += 18;

                while (bits >= 8)
                {
                    writer.Write((byte)buffer);
                    buffer >>= 8;
                    bits -= 8;
                }
            }

                return ret;
        }

        public MonHunCharacter(MemoryStream ms)
        {
            _reader = new BinaryReader(ms);
            itemBox = new MonHunItem[1400];

            _reader.BaseStream.Seek(0x0, SeekOrigin.Begin);
            name = System.Text.Encoding.UTF8.GetString(_reader.ReadBytes(32), 0, 32);
            playTime = _reader.ReadUInt32();
            zenny = _reader.ReadUInt32();
            hr = _reader.ReadUInt16();

            _reader.BaseStream.Seek(0x290, SeekOrigin.Begin);
            uint buffer = 0;
            uint bits = 0;
            for (int i = 0; i < 1400; i++)
            {
                byte b = 0;

                while (bits < 18)
                {
                    b = _reader.ReadByte();
                    buffer >>= 8;
                    buffer = (((uint)(b)) << 24) | (buffer & 0x00FFFFFF); // shift right into
                    bits += 8;
                }

                if(bits >= 18)
                {
                    uint item = (buffer >> ((int)(32-bits))) & 0x0003FFFF;
                    buffer = ((uint)b) << 24;
                    bits -= 18;
                    // Item OK
                    itemBox[i] = new MonHunItem(item & 0x7FF, item >> 11);
                }
            }
        }
    }

    public class MonHunItem
    {
        uint _id;
        uint _count;

        public uint ID { get { return _id; } set { _id = value & 0x7FF; } }
        public uint Count { get { return _count; } set { _count = value > 99 ? 99 : value; } }
        public string Name
        {
            get
            {
                if (_id < 1949)
                    return names[_id];
                else
                    return "<UNDEF>";
            }
        }

        public MonHunItem(uint id, uint count)
        {
            _id = id;
            _count = count;
        }

        public uint GetRaw()
        {
            return (((uint)_count) << 11) | ((uint)(_id));
        }

        public static string[] names = new string[] {
            "<null>",
"Formulation manual ① Introduction",
"Formulation manual ② beginner's class",
"Formulation manual ③ Intermediate Hen",
"Formulation certificate ④ Advanced",
"Formulation manual ⑤ master Hen",
"Book of storage good-technique",
"storage of good-force book",
"binoculars",
"recovery agents",
"recovery drugs Great",
"nutrients",
"nutrients Great",
"antidote",
"vitality agent",
"strength Hashikusuri",
"strength Hashikusuri Great",
"demon human drugs",
"demon human drugs Great",
"superhuman strength pills",
"sclerosing agent",
"sclerosing agent Great",
"patience pills",
"cooler drink",
"hot drinks",
"dissipation agent",
"clairvoyance of medicine",
"herbal medicine",
"nostrum",
"ancient elixir of",
"Genki Dorinko",
"life of dust",
"hunting skills drink",
"enhancer",
"explosive",
"powder of life",
"capture for anesthetic",
"Yukumo hot spring egg",
"Tan Zia Chips",
"the power of amulets",
"power nail",
"amulet of defense",
"claw of defense",
"broiler set",
"raw meat",
"poison raw meat",
"numbness raw meat",
"sleep raw meat",
"undercooked meat",
"browned meat",
"burnt meat",
"cooler meat",
"hot meat",
"Mosujaki",
"King Meet",
"Wheels",
"Boropikkeru",
"ice ax",
"ice ax Great",
"rag worms Ami",
"Mushiami",
"Mushiami Great",
"boomerang",
"throwing knives",
"poison throwing knives",
"sleep throwing knives",
"paralysis throwing knives",
"capture for anesthesia knife",
"material ball",
"paintball",
"flash ball",
"sound bomb",
"capture for anesthesia ball",
"Shonioidama",
"smoke ball",
"poison smoke ball",
"return ball",
"dung ball",
"Hun of monsters",
"trap tool",
"cobweb",
"net",
"pitfalls",
"numbness trap",
"barrel of the lid",
"small barrel",
"large barrel",
"small barrel bomb",
"large barrel bomb",
"large barrel bomb G",
"launch barrel bomb",
"launch barrel bomb G",
"item non-selection",
"satisfaction of blade drugs",
"heavy attack of the blade drugs",
"reduced air-edge drugs",
"mind's eye of the blade drugs",
"Kara real",
"Kara bone",
"LV1 usually bullets",
"LV2 Normal bullets",
"LV3 usually bullets",
"LV1 through bullets",
"LV2 through bullets",
"LV3 PierceS",
"LV1 shot",
"LV2 shotgun",
"LV3 shotgun",
"LV1 armor-piercing grenades",
"LV2 armor-piercing grenades",
"LV3 armor-piercing grenades",
"LV1 diffusion bullets",
"LV2 diffusion bullets",
"LV3 diffusion bullets",
"LV1 flame bullets",
"LV1 water-cooled bullet",
"LV1 blitz bullets",
"LV1 freezing bullets",
"LV1 Metsuryudan",
"LV1 poison bullets",
"LV2 poison bullets",
"LV1 paralysis bullets",
"LV2 paralysis bullets",
"LV1 sleep bullets",
"LV2 sleep bullets",
"LV1 Genkidan",
"LV2 Genkidan",
"LV1 recovery bullets",
"LV2 recovery bullets",
"paint bullet",
"capture for anesthesia bullets",
"LV1 usually bullets",
"LV2 Normal bullets",
"LV3 usually bullets",
"LV1 through bullets",
"LV2 through bullets",
"LV3 PierceS",
"LV1 shot",
"LV2 shotgun",
"LV3 shotgun",
"LV1 armor-piercing grenades",
"LV2 armor-piercing grenades",
"LV3 armor-piercing grenades",
"LV1 diffusion bullets",
"LV2 diffusion bullets",
"LV3 diffusion bullets",
"LV1 flame bullets",
"LV1 water-cooled bullet",
"LV1 blitz bullets",
"LV1 freezing bullets",
"LV1 Metsuryudan",
"LV1 poison bullets",
"LV2 poison bullets",
"LV1 paralysis bullets",
"LV2 paralysis bullets",
"LV1 sleep bullets",
"LV2 sleep bullets",
"LV1 Genkidan",
"LV2 Genkidan",
"LV1 recovery bullets",
"LV2 recovery bullets",
"paint bullet",
"capture for anesthesia bullets",
"gravel bullets",
"dragon 撃弾",
"LV1 Ki裂弾",
"LV2 Ki裂弾",
"LV1 blast bullets",
"LV2 blast bullets",
"demon human bullet",
"demon who satisfaction bullets",
"hardened bullet",
"curing tough bullets",
"LV1 little ammunition",
"LV2 little ammunition",
"LV1 double 撃弾",
"LV2 double 撃弾",
"staggering blow bullets",
"LV2 flame bullets",
"LV2 water-cooled bullet",
"LV2 blitz bullets",
"LV2 freezing bullets",
"LV2 Metsuryudan",
"LV1 through flame bullets",
"LV2 through flame bullets",
"LV1 through water-cooled bullet",
"LV2 through water-cooled bullet",
"LV1 through blitz bullets",
"LV2 through blitz bullets",
"LV1 through freezing bullets",
"LV2 through freezing bullets",
"LV1 large ammunition",
"LV2 large ammunition",
"LV1 far 撃弾",
"LV2 far 撃弾",
"continuous 爆榴 bullets",
"shrapnel",
"Retsuhikaridan",
"Dokukemuridan",
"flash bombs",
"manure bullet",
"healing vitality bullet",
"wide area recovery bullets",
"demon who curing bullets",
"RAPID",
"no bottle",
"empty bottles",
"LV1 Tsuyo撃 bottle",
"LV2 Tsuyo撃 bottle",
"LV1 attribute strengthening bottle",
"LV2 attribute strengthening bottle",
"Se' bottle",
"poison bottle",
"paralysis bottle",
"sleep bottle",
"Genki bottle",
"blast bottle",
"paint bottle",
"Yomushi extract",
"ChoYomushi extract",
"the power of growth bait",
"heavy growth bait",
"speed of growth bait",
"Mitsuesa of fire",
"water Mitsuesa",
"thunder Mitsuesa of",
"ice Mitsuesa",
"dragon Mitsuesa",
"on the power of growth bait",
"heavy on growth bait",
"speed of growth on food",
"especially on the growth of food force",
"especially on the growth bait heavy",
"speed, especially on the growth of food",
"flame Mitsuesa",
"running water of Mitsuesa",
"lightning Mitsuesa of",
"icing Mitsuesa",
"broken dragon Mitsuesa",
"extinguished of Mitsuesa",
"water outage Mitsuesa of",
"Zekkaminari Mitsuesa of",
"of crushed ice Mitsuesa",
"flashing dragon Mitsuesa",
"Makimodoshi Mitsuesa of",
"fishing earthworm",
"fishing Fibae",
"fishing frog",
"Sashimidango",
"Bakudango",
"golden dumpling",
"horn",
"recovery whistle",
"detoxification whistle",
"demon who whistle",
"curing whistle",
"burn garbage",
"honey",
"herb",
"detoxification grass",
"fire herb",
"ivy leaves",
"sleep grass",
"adhesive grass",
"Silvervine",
"Rakuyo grassroots",
"pepper",
"marbled grass",
"specialty mushroom kimchi",
"ice crystal strawberry",
"King cactus",
"Dosubisukasu",
"Oomorokoshi",
"Hoshimi of flowers",
"rainbow dandelion",
"Aokinoko",
"Nitorodake",
"Mahidake",
"poison Mount Tengu",
"Kutabiretake",
"pounding saw",
"Mandragora",
"chaos mushroom",
"Oomahishimeji",
"Koshikakedake",
"paint real",
"superhuman strength kind of",
"patience species of",
"cancellation real",
"dragon killing real",
"burst walnut",
"tension of the real",
"pierce the fruit of",
"diffusion real",
"Bae Pipo pumpkin",
"giant barrel acorn",
"Tongari acorn",
"Yukumo trees",
"Yukumo hardwood",
"stone",
"iron ore",
"earth of crystal",
"Makaraito ore",
"disk stone",
"ice crystal",
"Bearaito stone",
"Light Crystal",
"Doraguraito ore",
"Guren stone",
"lava mass",
"rash Light ore",
"Nova Crystal",
"Union ore",
"prison flame stone",
"rainbow-colored ore",
"water light original Pearl",
"YoShoHara Pearl",
"Shura original Pearl",
"lapis lazuli Gratama",
"armor stone",
"armor ball",
"top armor ball",
"Togayoroidama",
"Ken'yoroidama",
"heavy armor ball",
"mystery amulet",
"shining amulet",
"ancient amulet",
"rusty lump",
"ancient mass",
"undercooked fish",
"burnt fish",
"browned fish",
"sharpness",
"Sashimiuo",
"Nemurisakana",
"Harimaguro",
"swordfish",
"burst sardine",
"Kaku San pop-eyed goldfish",
"rupture arowana",
"explosion arowana",
"gluttony tuna",
"dos large eating tuna",
"ancient fish",
"small goldfish",
"Shindoiwashi",
"Ichino hairtail",
"beat swell shellfish",
"Yoroishidai",
"of ancient shark skin",
"spring night carp",
"giant tail Gael",
"dead insect",
"immortality insects",
"bitter worms",
"light Mushi",
"lightning insects",
"Bonbatta",
"Tsuchihachinoko",
"Setchakuroari",
"Kira Beetle",
"dos Hercules",
"super power lightning insects",
"royal beetle",
"Marekogane",
"Hanasuzumushi",
"Ootsunoageha",
"Omma swallowtail",
"Oonanahoshi",
"poison cloud",
"giant poison cloud",
"蝕龍 Mushi",
"keel [small]",
"keel [medium]",
"keel [large]",
"mystery of bone",
"skull of mystery",
"above keel",
"apex keel",
"Ken keel",
"Koryukotsu",
"fine bird keel",
"animal bones",
"large bones",
"robust bone",
"ancient Ryukotsu of",
"variant of bone",
"variant Ken bone",
"dragon Fang",
"dragon claw",
"sharp claws",
"sharp tusks",
"bird dragon ball",
"dragon ball",
"Gu Long of blood",
"Gu Long of Kiyoshichi",
"Steel of eggs",
"silver eggs",
"gold egg",
"off ale ice ax",
"squeal bag",
"poison bag",
"deadly poison bag",
"paralysis bag",
"strong paralysis bag",
"sleeping bag",
"coma bag",
"flame bag",
"explosive flame bag",
"electrical bag",
"blitz bags",
"frozen bag",
"water bag",
"flood bag",
"Kyohashi extract",
"albino extract",
"ferocity of extract",
"ferocious fangs",
"ferocious Surudokiba",
"ferocious claws",
"ferocious Togatsume",
"ferocious keel",
"ferocious cuspate",
"ferocious flame bag",
"ferocious flame scales",
"ferocious water bag",
"ferocious body fluids",
"ferocious electrical bag",
"ferocious charging shell",
"ferocious charge hair",
"ferocious ice cubes",
"ferocious 蝕龍 scales",
"ferocious venom",
"ferocious paralysis venom",
"ferocious sleeping bag",
"ferocious sleep venom",
"ferocious 爆液",
"cat hair of ruby",
"neck tinnitus dragon skin",
"round bird feather",
"Kumohitsujishika corner of",
"Kumohitsujishika hairball",
"Kelvin corner of",
"warm fur",
"fine fur",
"Gaushika corner of",
"herbivorous dragon of crustaceans",
"herbivorous dragon of Ken shell",
"herbivorous dragon head shell",
"vertical skin dragon epithelial",
"body fluids of monsters",
"concentrated juice of monsters",
"of flying beetle crustaceans",
"flying beetle of Ken shell",
"of flying beetle wings",
"large jaw of beetle",
"beetle belly bag",
"fine belly bag",
"crustaceans of Langosta",
"Ken shell of Langosta",
"Langosta feathers",
"Langosta of thin wings",
"crustaceans of kantharos",
"kantharos Kenkara of",
"kantharos feathers",
"Kantharos of thin wings",
"kantharos head of",
"shield insects crustaceans",
"Ken shell of the shield insect",
"wing snake dragon skin",
"wing snake dragon epithelial",
"skin striped",
"wing snake dragon head",
"bird dragon species of Fang",
"Makkao scales",
"scales on the Makkao",
"Makkao skin",
"跳狗 dragon scales",
"跳狗 dragon on scales",
"跳狗 dragon of red skin",
"跳狗 dragon on red skin",
"champion of crown feathers",
"跳狗 dragon of postabdominal spine",
"Jagyi scales",
"Jagyi",
"Jagyi skin",
"Ranposu scales",
"scales on the Ranposu",
"Ranposu skin",
"Ranposu epithelium",
"Ranposu Daikawa of",
"Ranposu large epithelium of",
"Ranposu Daitsume of",
"large of Ranposu Togatsume",
"Dosuranposu head of",
"Geneposu of paralysis fang",
"Geneposu scales",
"scales on the Geneposu",
"Geneposu skin",
"Geneposu epithelium",
"Geneposu Daikawa of",
"Geneposu large epithelium of",
"Geneposu Daikiba of",
"large of Geneposu Togakiba",
"Dosugeneposu head of",
"poison fang of Eos",
"Eos scales",
"scales on the Eos",
"Eos skin",
"Eos epithelium",
"Eos Daikawa of",
"Eos large epithelium of",
"Eos Murasakiuroko of",
"on the Eos Murasakiuroko",
"Dosuiosu head of",
"Gianosu scales",
"scales on the Gianosu",
"Gianosu skin",
"Gianosu epithelium",
"hair blue bear beast",
"the bristles of the blue bear beast",
"crustaceans of blue bear beast",
"Ken shell of blue bear beast",
"vambrace of blue bear beast",
"Ken'udekabuto of blue bear beast",
"hair red helmet",
"bristle of red helmet",
"red helmet of crustaceans",
"red helmet of Ken shell",
"crimson helmet Furious",
"red helmet of rage hair",
"hair of white rabbits Beast",
"the bristles of the white rabbit beast",
"white rabbits beast ear of",
"white rabbits beast of large ear",
"White Rabbit Beast plastron of",
"Ken plastron of white rabbits Beast",
"ice claws of the white rabbit beast",
"of white rabbit beast Kotsume",
"heavy snow Lord of hair",
"heavy snow Lord of the bristles",
"heavy snow Lord plastron",
"heavy snow Lord Kenharakabuto",
"crustaceans of red instep Beast",
"Ken shell of red instep Beast",
"nail red instep Beast",
"red instep Beast Togatsume",
"bellows instep of red instep Beast",
"Kaitori scales",
"scales on the Kaitori",
"crustaceans of Kaitori",
"Ken shell of Kaitori",
"Kaitori ear of",
"Kaitori long ears of",
"huge beak",
"fine beak",
"Kaitori wing membrane of",
"ferocity of Kaitoriuroko",
"skin of rubber",
"epithelium of rubber",
"Dokukaitori wing membrane of",
"Dokukaitori wings",
"Dokukaitori head of",
"ferocious Kadoku Kaitorigawa",
"nocturnal bird Haneuroko of",
"nocturnal bird on the wing scales of",
"nocturnal bird wing membrane of",
"nocturnal bird wings",
"wing claws of the nocturnal bird",
"sharp wing claws of the nocturnal bird",
"nocturnal bird ear of",
"nocturnal bird tail feathers of",
"nocturnal bird of gold feathers",
"ferocious Kayoru Toba",
"scales of black wolf bird",
"scales on top of the black wolf bird",
"crustaceans of black wolf bird",
"Ken shell of black wolf bird",
"ear of black wolf bird",
"long ears of black wolf bird",
"pointed beak",
"squid was beak",
"wing of black wolf bird",
"Tail of black wolf bird",
"mane of black wolf bird",
"ferocious Kakuro Okamitoriuroko",
"Sekigan scales",
"scales on the Sekigan",
"crustaceans of Sekigan",
"Ken shell of Sekigan",
"Moss moss skin",
"Fango fur",
"fur on top of the Fango",
"Fango head of",
"large boar skin",
"hard of large wild boar skin",
"tusks of large boar",
"large boar Daikiba",
"Burango hair",
"bristles of Burango",
"snow lion hair",
"snow lion bristles",
"snow lion Fang",
"snow lion Surudokiba",
"snow lion beard",
"snow lion tail",
"ferocity of snow lion hair",
"bristles of Kisarukitsune",
"Kisarukitsune Ken long bone of",
"Kisarukitsune claw of",
"large ear of Kisarukitsune",
"Kisarukitsune tail of",
"ferocious oyster Sarukitsuneke",
"small shell of the shrimp",
"shrimp Daikara",
"sand dragon scales",
"sand dragon on scales",
"sand dragon Fin",
"sand dragon on fin",
"sand dragon Fang",
"sand dragon of Surudokiba",
"scales on top of the water dragon",
"fin on top of the water dragon",
"water dragon of Surudokiba",
"water dragon wings film",
"water dragon of your head",
"ferocious Kamizu Ryuuroko",
"lava dragon on scales",
"lava dragon of Ken shell",
"lava dragon of Surudokiba",
"lava dragon on fin",
"ferocity of lava Ryuuroko",
"skin of aquatic beast",
"epithelium of the aquatic beast",
"immature spongy",
"skin of cancellous bone",
"epithelium of cancellous bone",
"scales of water beast",
"scales on the water beast",
"claw of water beast",
"water beast Surudotsume",
"water beast comb",
"exclusive comb",
"tail water beast",
"ferocity Kamizu beast scales",
"latent opening dragon of crustaceans",
"latent opening dragon of Ken shell",
"latent opening dragon skin",
"latent opening dragon epithelial",
"latent opening dragon claw",
"latent opening dragon of Togatsume",
"latent opening dragon head shell",
"vivid body fluids",
"richly-colored body fluids",
"ferocious river ports Ryukara",
"Kairyu skin",
"Kairyu epithelial",
"Kairyu scales",
"Kairyu on scales",
"back conductive shell of Kairyu",
"high-voltage shell of Kairyu",
"corner of Kairyu",
"Kairyu apex corner of",
"Kairyu tail of",
"nail Kairyu",
"Kairyu Surudotsume of",
"Kairyu anger of",
"Kairyu AoiTama of",
"ferocity of Kairyu skin",
"scales of lava beast",
"scales on top of the lava beast",
"flame halberd dragon of 燃鱗",
"flame halberd dragon of Ken shell",
"flame halberd dragon epithelial",
"flame halberd dragon of Surudotsume",
"flame halberd dragon on fin",
"flame halberd dragon of the anchor hole",
"flame halberd dragon's tail",
"Kenmunekara was red-hot",
"ferocity of flame halberd Ryukara",
"Onikaeru scales",
"scales on the Onikaeru",
"crustaceans of Onikaeru",
"Ken shell of Onikaeru",
"nail Onikaeru",
"Onikaeru Togatsume of",
"Onikaeru Daikiba of",
"huge tusks of Onikaeru",
"stern skull",
"Kawazu oil",
"Kawazu gluteal oil",
"ferocity of Onikaeruuroko",
"Iwa穿 scales",
"scales on the Iwa穿",
"crustaceans of Iwa穿",
"Ken shell of Iwa穿",
"huge tusks of Iwa穿",
"Iwa穿 maximum Fang",
"sharkskin scales",
"thick epithelium",
"garbled shark epithelial",
"of garbled shark on scales",
"of garbled shark fin on",
"garbled shark of sawtooth",
"blade tail of garbled shark",
"ferocity of garbled Sharkskin",
"crustaceans of Shibohebiryu",
"Ken shell of Shibohebiryu",
"Shibohebiryu skin",
"Shibohebiryu epithelium",
"Shibohebiryu of bone marrow",
"Shibohebiryu of the medulla oblongata",
"Shibohebiryu Nakabuto of",
"on the Shibohebiryu Nakabuto",
"Shibohebiryu Fang",
"feel a shudder of cold beak",
"ferocity of Shibohebi Ryukara",
"black pearl",
"crown shell",
"rotting crimson corner",
"small shell of Tatekani",
"crustaceans of Tatekani",
"Ken shell of Tatekani",
"nail Tatekani",
"Tatekani Togatsume of",
"ferocity of Tatekanikara",
"crustaceans of Hoko砕",
"Ken shell of Hoko砕",
"nail Hoko砕",
"Hoko砕 Togatsume of",
"small shell of Kamakani",
"crustaceans of Kamakani",
"Ken shell of Kamakani",
"legs of Kamakani",
"Kamakani Ken'ashi of",
"nail Kamakani",
"Kamakani Togatsume of",
"ferocity of Kamakanikara",
"Toru Ken shell of the beetle",
"Toru thin wings of beetles",
"Toru apex corner of the beetle",
"Ken shell heavy beetle",
"heavy beetle Kenmunekara",
"heavy beetle Surudotsume",
"large jaw heavy beetle",
"Entsuki tail heavy beetle",
"heavy armor extract",
"ferocity of heavy beetle shell",
"爆鎚 dragon scales",
"爆鎚 dragon on scales",
"爆鎚 dragon of crustaceans",
"爆鎚 dragon of Ken shell",
"爆鎚 dragon jaw",
"爆鎚 dragon of the heat-resistant shell",
"爆鎚 dragon of bone marrow",
"爆鎚 dragon of ruby",
"ferocity of 爆鎚 Ryuuroko",
"Takaramatoi scales",
"scales on the Takaramatoi",
"Takaramatoi treasure jaw",
"Takaramatoi treasure jaw",
"TakaraIwakatamari",
"crustaceans of 砕竜",
"Ken shell of 砕竜",
"black 砕竜 曜甲",
"Ken 砕竜 black 曜甲",
"砕竜 head shell of",
"peak shell of 砕竜",
"mysterious slime mold",
"砕竜 fist of",
"砕竜 Gouken of",
"砕竜 tail of",
"砕竜 of bone marrow",
"砕竜 jewel of",
"ferocity of 砕竜 shell",
"Ken shell of Otsuchiryu",
"Otsuchiryu Kenkokekabuto of",
"tail hammer dragon of Cobb",
"Otsuchiryu Ken'okabuto of",
"Otsuchiryu apex corner of",
"Otsuchiryu of sacrum",
"ferocious face hammer Ryukara",
"boggy rinds",
"pearl-colored soft leather",
"albino Nakaochi",
"albino of marbling",
"ferocity Kashiro soft skin",
"迅竜 scales",
"scales on the 迅竜",
"迅竜 black hair of",
"on the 迅竜 Japanese Black",
"迅竜 tail of",
"迅竜 postabdominal spine of",
"迅竜 blade wings",
"迅竜 of sharp blade wing",
"迅竜 Fang",
"迅竜 Surudokiba of",
"迅竜 of bone marrow",
"迅竜 of the medulla oblongata",
"ferocity of 迅竜 scales",
"white Gale scales",
"white Gale Ueuroko",
"white Gale Japanese Black",
"white Gale on Japanese Black",
"female fire dragon scales",
"scales on top of the female fire dragon",
"female fire dragon of crustaceans",
"female fire dragon of Ken shell",
"female fire dragon wings film",
"female fire dragon of thorns",
"thorn on top of the female fire dragon",
"female fire dragon anger",
"female fire dragon ruby",
"ferocity Kamesu fire Ryuuroko",
"Murasakidokuhime scales",
"scales on the Murasakidokuhime",
"crustaceans of Murasakidokuhime",
"Ken shell of Murasakidokuhime",
"gold fire dragon on scales",
"gold fire dragon of Ken shell",
"gold fire dragon on thorns",
"ferocious gold fire Ryuuroko",
"fire dragon scales",
"fire dragon on scales",
"fire dragon of crustaceans",
"fire dragon of Ken shell",
"fire dragon wings film",
"fire dragon wings",
"fire dragon's tail",
"fire dragon of anger",
"fire dragon of ruby",
"ferocity of fire Ryuuroko",
"black flames King of scales",
"scales on top of the Black Flame King",
"crustaceans of the Black Flame King",
"Ken shell of the Black Flame King",
"silver fire dragon on scales",
"silver fire dragon of Ken shell",
"silver fire dragon's tail",
"ferocious silver fire Ryuuroko",
"fire dragon wings nail",
"fire dragon of bone marrow",
"fire dragon of the medulla oblongata",
"fire dragon of 煌液",
"thunder wolf dragon of crustaceans",
"thunder wolf dragon of Ken shell",
"thunder wolf dragon of charge hair",
"thunder wolf dragon of high Denke",
"thunder wolf dragon corner",
"thunder wolf dragon of cuspate",
"thunder wolf dragon claw",
"thunder wolf dragon of Togatsume",
"thunder wolf dragon's tail",
"thunder wolf dragon of the power storage shell",
"high-voltage shell of thunder wolf dragon",
"thunder wolf dragon of anger",
"thunder wolf dragon of jasper",
"ferocity Kakaminari wolf Ryukara",
"gold crustaceans of Raikou",
"gold Ken shell of Raikou",
"gold Raikou charged hair",
"gold Raikou high Denke",
"gold Raikou 旋角",
"gold Raikou large 旋角",
"power dragon scales",
"power dragon on scales",
"power dragon of Togekara",
"power dragon of Kentogekara",
"power dragon of charged membranes",
"power dragon of high conductive film",
"power dragon wings nail",
"power dragon of sharp wing claws",
"power dragon of Kanmurikabuto",
"power dragon of Kenkanmurikabuto",
"power dragon of 鋏尾",
"piezoelectric instep",
"high pressure Denkabuto",
"power dragon of anger",
"power dragon of lightning ball",
"ferocity of electricity Ryuuroko",
"behemoth hair",
"the bristles of the behemoth",
"crustaceans behemoth",
"Ken shell of behemoth",
"behemoth Fang",
"behemoth Kenkiba of",
"behemoth nasal spine of",
"behemoth redhead",
"Yukikabutokatamari",
"Yukikabuto Daikatamari",
"behemoth head shell of",
"behemoth of ice ball",
"ferocity of behemoth hair",
"Awakitsuneryu scales",
"scales on the Awakitsuneryu",
"Awakitsuneryu Murasakike of",
"Awakitsuneryu purple on the hair of",
"nail Awakitsuneryu",
"Awakitsuneryu Togatsume of",
"Awakitsuneryu of Nishiki fin",
"Awakitsuneryu UeNishiki fin of",
"Awakitsuneryu tail of",
"bubbling synovial fluid",
"bubbling above the synovial fluid",
"Awakitsuneryu anger of",
"Awakitsuneryu of polka dot",
"ferocity of Awakitsuneryuuroko",
"Kiryu scales",
"scales on the Kiryu",
"crustaceans of Kiryu",
"Ken shell of Kiryu",
"Kiryu Fang",
"Kiryu Surudokiba of",
"flame-shaped shell of Kiryu",
"flame-shaped shell of Kiryu",
"Kiryu tail of",
"Kiryu tail blade piece of",
"red-hot flame sac",
"Benihomura嚢 was red-hot",
"Kiryu anger of",
"Kiryu of flame ball",
"ferocity of Kiryuuroko",
"燼滅 blade of scales",
"燼滅 scales on top of the blade",
"燼滅 blade of crustaceans",
"燼滅 blade Ken shell of",
"燼滅 dust powder blade",
"TodorokiRyu scales",
"scales on the TodorokiRyu",
"crustaceans of TodorokiRyu",
"Ken shell of TodorokiRyu",
"TodorokiRyu tail of",
"nail TodorokiRyu",
"TodorokiRyu Togatsume of",
"TodorokiRyu Fang",
"TodorokiRyu Surudokiba of",
"TodorokiRyu head shell of",
"TodorokiRyu Agito of",
"ferocious Katodoroki Ryuuroko",
"rough claw scales",
"rough claw on scales",
"rough claw crustacean",
"Ken rough claw shell",
"rough claw Aoitsume",
"rough claw Daiaotsume",
"thousand blade dragon of blade scales",
"thousand blade dragon of the sharp blade scales",
"thousand blade dragon flying blade pieces",
"thousand blade dragon flying blade",
"thousand blade dragon claw",
"thousand blade dragon of Kokutsume",
"thousand blade dragon spear tail",
"thousand blade dragon sword angle",
"thousand blade dragon Kikatana angle of",
"thousand blade dragon wings nail",
"thousand blade dragon of Togatsubasatsume",
"thousand blade dragon of the anti-anger",
"ferocity of thousand blade dragon scales",
"black 蝕竜 scales",
"scales on the black 蝕竜",
"crustaceans of black 蝕竜",
"Ken shell of black 蝕竜",
"dark wings of black 蝕竜",
"dark wings on the black 蝕竜",
"black 蝕竜 Mugotsume of",
"black 蝕竜 of sharpness Mugotsume",
"black 蝕竜 tail of",
"black 蝕竜 anger of",
"black 蝕竜 darkness ball of",
"black 蝕竜 antennal",
"black 蝕竜 leaflet antennae",
"unclean Ryuuroko",
"ferocity of black 蝕竜 scales",
"heaven around dragon scales",
"heaven around a dragon on scales",
"heaven around the dragon of crustaceans",
"heaven around dragon Ken shell",
"heaven around the dragon of the rainbow wing",
"heaven around on top of the dragon Nijitsubasa",
"heaven around dragon Kiyoshitsume",
"heaven around dragon SurudoKiyoshitsume",
"heaven around the dragon's tail",
"heaven around the dragon of anger",
"heaven around the dragon of light ball",
"heaven around the dragon of the corner",
"heaven around dragon cuspate",
"pure white Ryuuroko",
"gold lion of cuspate",
"gold lion of Surudokiba",
"gold lion of Japanese Black",
"gold lion of Togatsume",
"gold lion's tail",
"golden hair",
"gold lion of Furious",
"gold lion of Fighting Spirit",
"gold angle of Rasetsu",
"ferocious gold lion hair",
"fear 暴竜 of black scales",
"fear 暴竜 of black leather",
"fear 暴竜 Daikiba of",
"fear 暴竜 claw of",
"fear 暴竜 head shell of",
"fear 暴竜 tail of",
"fear 暴竜 of saliva",
"dos black blood",
"veteran of jet-black skin",
"fear 暴竜 jewel of",
"ferocity Kaosore 暴竜 scales",
"thunder angle of giraffe",
"giraffe skin",
"giraffe epithelial",
"giraffe mane",
"giraffe of Kaminario",
"Ao angle of giraffe",
"Steel Dragon crustaceans",
"Steel Dragon Ken shell",
"of steel Ryuuroko",
"on top of the steel Ryuuroko",
"steel dragon wing membrane",
"corner of the steel dragon",
"Steel Dragon cuspate",
"of steel dragon tail",
"Steel dragon claw",
"of steel dragon Togatsume",
"Steel Dragon Jewel",
"Chameleos of skin",
"Chameleos epithelial",
"Chameleos corner",
"Chameleos of cuspate",
"Chameleos of nails",
"Chameleos of Togatsume",
"Chameleos of the wing membrane",
"haze dragon tail",
"Chameleos of jewel",
"flame King Dragon of crustaceans",
"flame king dragon Ken shell",
"flame king dragon mane",
"flame king dragon tail",
"flame King Dragon corner",
"flame king dragon cuspate",
"flame Ryuuroko",
"prison flame Ryuuroko",
"flame dragon claw",
"flame dragon Togatsume",
"flame dragon wing membrane",
"flame dragon dust powder",
"flame dragon jewel",
"Dairyu crystal",
"scales on the Haryu",
"Ken shell of Haryu",
"Haryu tail of",
"Haryu Tsuyoshitsume of",
"Haryu Daikiba of",
"Haryu large thorns",
"Haryu jewel of",
"Ken shell of Kuzureryu",
"Kuzureryu of belly scales",
"Kuzureryu tail of",
"Kuzureryu 穿爪 of",
"Kuzureryu of cutting jaw",
"fin on top of the Kuzureryu",
"Kuzureryu jewel of",
"煌黒 dragon Ken reverse shell",
"煌黒 dragon of anger",
"煌黒 dragon Togatsume",
"煌黒 dragon wing membrane",
"煌黒 dragon tail",
"informal heaven angle",
"through the heaven corner",
"lapis lazuli color Ryudama of",
"Ken shell of ArashiRyu",
"ArashiRyu Fei film",
"ArashiRyu corner of",
"sharp claws of ArashiRyu",
"ArashiRyu tail of",
"ArashiRyu Munekara of",
"storm alveoli",
"sky of Ryudama",
"Mukuro body shell",
"Kenmukurotai shell",
"Mukurotogekara",
"Togamukurotogekara",
"Mukuro skull",
"Mukuro vertebra",
"Mukuro dragon of blue mottled skin",
"Mukuro dragon mouth arm instep",
"Mukuro dragon 喰砕 Fang",
"Mukuro dragon squid bone",
"Mukuro dragon of the remaining 魄玉",
"emission to mucus",
"mucus on which emits light",
"map",
"emergency medicine",
"emergency medicine Great",
"mobile food",
"mobile broiler set",
"mobile grindstone",
"mobile numbness trap",
"paid only flash ball",
"paid only sound bomb",
"paid only nostrum",
"of payment for life dust",
"paid only pitfall",
"large barrel bomb for payment",
"paid hunting skills drink",
"varistor of bullet",
"single restraint bullets",
"pair 巨龍 bomb",
"cat Taku ticket",
"rusty debris",
"ancient debris",
"ominous cloth",
"ominous darkness cloth",
"luxurious relic",
"ultra-luxurious relics",
"chipped stone statue",
"chipped large stone statue",
"black pieces",
"black mass",
"Airou kettle to boil water",
"Yukumo glutinous rice",
"stuffed toy set",
"mystery of the weapon of secret notes",
"secret notes of the heavy crossbow of mystery",
"dining credit",
"fine dining credit",
"courage proof of",
"courage of proof G",
"hope of testimony",
"hope of proof G",
"meat ball stamp",
"Berna ticket",
"cocotte ticket",
"pocket ticket",
"Yukumochiketto",
"Ryurekiin ticket",
"Otomo ticket",
"airship ticket",
"bistro ticket",
"trade ticket",
"footbath ticket",
"Guild ticket",
"Black Obi ticket",
"Tatsu Jin ticket",
"Den Seth ticket",
"edible wild plants set voucher",
"edible wild plants set voucher G",
"edible wild plants set voucher of steel",
"silver edible wild plants set voucher",
"gold edible wild plants set voucher",
"EX fire dragon ticket",
"EX fire dragon ticket S",
"EX lava dragon ticket",
"EX TodorokiRyu ticket",
"EX TodorokiRyu ticket S",
"EX Kaminariokamiryu ticket",
"EX 砕竜 ticket",
"EX black 蝕竜 ticket",
"EX TenMawariryu ticket",
"EX steel dragon ticket",
"EX Chameleos ticket",
"EX Honooo dragon ticket",
"EX gold fire dragon ticket",
"EX silver fire dragon ticket",
"proof of the ferocity of hunting Ⅰ",
"proof of the ferocity of hunting Ⅱ",
"proof of the ferocity of hunting Ⅲ",
"1 proof of red helmet hunting",
"red helmet hunting of proof 2",
"testimony 3 of red helmet hunting",
"proof 4 of crimson helmet hunting",
"proof of red helmet hunting 5",
"proof of red helmet hunting 6",
"proof of red helmet hunting 7",
"proof of red helmet hunting 8",
"red helmet hunting of testimony 9",
"10 testimony of red helmet hunting",
"proof of heavy snow main hunting 1",
"proof of heavy snowfall main hunting 2",
"testimony 3 of heavy snow main hunting",
"proof of heavy snow main hunting 4",
"proof of heavy snow main hunting 5",
"proof of heavy snow main hunting 6",
"proof of heavy snow main hunting 7",
"proof of heavy snow main hunting 8",
"proof of heavy snow main hunting 9",
"10 testimony of heavy snow main hunting",
"proof of pike 砕狩 hunting 1",
"pike 砕狩 hunting of proof 2",
"pike 砕狩 hunting of testimony 3",
"pike 砕狩 hunting of proof 4",
"proof of pike 砕狩 hunting 5",
"pike 砕狩 hunting of testimony 6",
"proof of pike 砕狩 hunting 7",
"pike 砕狩 hunting of proof 8",
"pike 砕狩 hunting of testimony 9",
"pike 砕狩 hunting of proof 10",
"Murasakidokuhime hunting of proof 1",
"Murasakidokuhime hunting of proof 2",
"Murasakidokuhime hunting of testimony 3",
"Murasakidokuhime hunting of proof 4",
"Murasakidokuhime hunting of testimony 5",
"Murasakidokuhime hunting of testimony 6",
"Murasakidokuhime hunting of proof 7",
"Murasakidokuhime hunting of proof 8",
"Murasakidokuhime hunting of testimony 9",
"Murasakidokuhime hunting of proof 10",
"1 proof of rock 穿狩 hunting",
"rock 穿狩 hunting of proof 2",
"rock 穿狩 hunting of testimony 3",
"rock 穿狩 hunting of proof 4",
"rock 穿狩 hunting of testimony 5",
"rock 穿狩 hunting of testimony 6",
"rock 穿狩 hunting of proof 7",
"rock 穿狩 hunting of proof 8",
"rock 穿狩 hunting of testimony 9",
"rock 穿狩 hunting of proof 10",
"1 proof of white Gale hunting",
"white Gale hunting of proof 2",
"testimony 3 of white Gale hunting",
"white Gale hunting of proof 4",
"proof of white Gale hunting 5",
"white Gale hunting of testimony 6",
"proof of white Gale hunting 7",
"white Gale hunting of proof 8",
"white Gale hunting of testimony 9",
"10 testimony of white Gale hunting",
"Takaramatoi hunting of proof 1",
"Takaramatoi hunting of proof 2",
"Takaramatoi hunting of testimony 3",
"Takaramatoi hunting of proof 4",
"Takaramatoi hunting of testimony 5",
"Takaramatoi hunting of testimony 6",
"Takaramatoi hunting of proof 7",
"Takaramatoi hunting of proof 8",
"Takaramatoi hunting of testimony 9",
"Takaramatoi hunting of proof 10",
"Sekigan hunting of proof 1",
"Sekigan hunting of proof 2",
"Sekigan hunting of testimony 3",
"Sekigan hunting of proof 4",
"Sekigan hunting of testimony 5",
"Sekigan hunting of testimony 6",
"Sekigan hunting of proof 7",
"Sekigan hunting of proof 8",
"Sekigan hunting of testimony 9",
"Sekigan hunting of proof 10",
"1 proof of Black Flame King hunting",
"black flames King hunting of proof 2",
"testimony 3 of Black Flame King hunting",
"proof 4 of Black Flame King hunting",
"proof of Black Flame King hunting 5",
"black flames King hunting of testimony 6",
"proof of Black Flame King hunting 7",
"proof of Black Flame King hunting 8",
"proof of Black Flame King hunting 9",
"10 testimony of Black Flame King hunting",
"gold Raikou hunting of proof 1",
"gold Raikou hunting of proof 2",
"gold Raikou hunting of testimony 3",
"gold Raikou hunting of proof 4",
"gold Raikou hunting of testimony 5",
"gold Raikou hunting of testimony 6",
"gold Raikou hunting of proof 7",
"gold Raikou hunting of proof 8",
"gold Raikou hunting of testimony 9",
"gold Raikou hunting of proof 10",
"rough claw hunting of proof 1",
"rough claw hunting of proof 2",
"rough claw hunting of testimony 3",
"rough claw hunting of proof 4",
"rough claw hunting of testimony 5",
"rough claw hunting of testimony 6",
"rough claw hunting of proof 7",
"rough claw hunting of proof 8",
"rough claw hunting of testimony 9",
"rough claw hunting of proof 10",
"燼滅 blade hunting of proof 1",
"燼滅 blade hunting of proof 2",
"燼滅 blade hunting of testimony 3",
"燼滅 blade hunting of proof 4",
"燼滅 blade hunting of testimony 5",
"燼滅 blade hunting of testimony 6",
"燼滅 testimony of blade hunting 7",
"燼滅 blade hunting of proof 8",
"燼滅 blade hunting of testimony 9",
"燼滅 blade hunting of proof 10",
"Royal Honey",
"specialty mushroom",
"carefully mushroom",
"aging mushroom",
"Dosumatsutake",
"deep mushroom",
"specialty bamboo shoots",
"tropical strawberry",
"snow mountain grass",
"specialty mainspring",
"carefully mainspring",
"golden fish",
"white goldfish",
"Nishikisakana",
"ONishikisakana",
"Torosashimiuo",
"Royal Kabuto",
"God helmet",
"silver cricket",
"gold cricket",
"eternal youth moth",
"large ageless moth",
"piece of golden stone",
"mass of golden stone",
"floral stone pieces of",
"floral stone mass of",
"dragon piece of amber",
"dragon amber mass of",
"keel crystal",
"blood stone",
"Fukachiseki",
"燃石 charcoal",
"strength 燃石 coal",
"fossil bone",
"rotten Ryuuroko",
"white lever",
"Shidekawayu",
"secret pouch",
"perfectly round acorn",
"beautiful belly bag",
"shining Harabukuro",
"monster of liver",
"fish dragon of liver",
"Poponotan",
"Apukerosu of liver",
"ancient tree nuts",
"deep water lily roots of",
"deep water lily of the tuberous root",
"Kumohitsujishika natural hair",
"Gagua eggs",
"gold Gagua eggs",
"dragon eggs",
"rough ash crystal",
"gemstone of white crystal",
"gunpowder rock",
"carnivorous dragon eggs",
"large chunks of meteorite",
"Kuon fossil of",
"Guild flag",
"Hun Gagua",
"Hun territory",
"large Hun territory",
"soldier of pheromone",
"Queen of pheromone",
"Gama of tears",
"Gama of large tears",
"Zazamiso",
"best Zazamiso",
"Yad pearl",
"best Yad pearl",
"dragon of Tears",
"dragon of large tears",
"Kibajuu tears of",
"large fangs Beast tears",
"dragon treasure",
"ancient dragon treasure",
"today dragon crystal shards",
"mad dragon crystal",
"ominous mad dragon crystal",
"furfuraldehyde baby",
"furfuraldehyde coin",
"Gararakoin",
"Reusukoin",
"Kechakoin",
"Ganosukoin",
"Burakikoin",
"Geryosu coin",
"Dosukoin",
"rustic mill ends",
"rustic top material",
"stylish end material",
"stylish top material",
"end material of the ore",
"the upper material of the ore",
"end material of insects",
"top material of insects",
"end material of the bone",
"the upper material of the bone",
"end material of wood",
"top material of wood",
"fur scraps of",
"fur top material",
"herbivorous dragon of the end material",
"herbivorous dragon of the upper material",
"vertical skin dragon of the upper material",
"flying beetle end material",
"flying beetle top material",
"dog dragon of the end material",
"dog dragon of the upper material",
"跳狗 dragon of the end material",
"跳狗 dragon of the upper material",
"Ranposu end material",
"Ranposu top material",
"Geneposu end material",
"Geneposu top material",
"Eos end material",
"Eos top material",
"blue bear beast end material",
"blue bear beast top material",
"red helmet end material",
"red helmet of inscription end material",
"White Rabbit Beast end material",
"White Rabbit Beast top material",
"heavy snow Lord of the end material",
"heavy snow Lord inscription end material",
"scraps of red instep Beast",
"top material of red instep Beast",
"Kaitori end material",
"Kaitori top material",
"Takeshi end material of Kaitori",
"Dokukaitori end material",
"Dokukaitori top material",
"Takeshi end material of Dokukaitori",
"nocturnal bird end material",
"nocturnal bird top material",
"Takeshi end material of nocturnal bird",
"end material of black wolf bird",
"top material of black wolf bird",
"Takeshi end material of black wolf bird",
"Sekigan end material",
"Sekigan inscription scraps of",
"large boar end material",
"large boar top material",
"snow lion end material",
"snow lion top material",
"snow lion Takeshi end material",
"Kisarukitsune top material",
"Takeshi end material of Kisarukitsune",
"sand dragon of the end material",
"sand dragon of the upper material",
"water dragon of the upper material",
"water dragon of Takeshi end material",
"lava dragon of the upper material",
"lava dragon of Takeshi end material",
"end material of the water beast",
"the upper material of the water beast",
"Takeshi end material of the water beast",
"latent opening dragon of the end material",
"latent opening dragon of the upper material",
"latent opening dragon of Takeshi end material",
"Kairyu end material",
"Kairyu top material",
"Kairyu Takeshi end material",
"flame halberd dragon of the upper material",
"flame halberd dragon of Takeshi end material",
"Onikaeru end material",
"Onikaeru top material",
"Takeshi end material of Onikaeru",
"Iwa穿 end material",
"Iwa穿 inscription scraps of",
"garbled shark top material",
"Takeshi scraps of garbage shark",
"Shibohebiryu end material",
"Shibohebiryu top material",
"Takeshi end material of Shibohebiryu",
"Tatekani end material",
"Tatekani top material",
"Takeshi end material of Tatekani",
"Hoko砕 end material",
"Hoko砕 inscription scraps of",
"Kamakani end material",
"Kamakani top material",
"Takeshi end material of Kamakani",
"heavy beetle top material",
"Takeshi end material heavy beetle",
"爆鎚 dragon of the end material",
"爆鎚 dragon of the upper material",
"爆鎚 dragon of Takeshi end material",
"Takaramatoi end material",
"Takaramatoi inscription scraps of",
"砕竜 end material",
"砕竜 top material",
"Takeshi end material of 砕竜",
"Otsuchiryu top material",
"Takeshi end material of Otsuchiryu",
"boggy the end material",
"pearl color top material",
"pearl color Takeshi end material",
"迅竜 end material",
"迅竜 top material",
"Takeshi end material of 迅竜",
"white Gale end material",
"white Gale inscription end material",
"female fire dragon of the end material",
"female fire dragon of the upper material",
"female fire dragon of Takeshi end material",
"Murasakidokuhime end material",
"Murasakidokuhime inscription scraps of",
"fire dragon of the end material",
"fire dragon of the upper material",
"fire dragon of Takeshi end material",
"black flames King of end material",
"black flames King of inscription end material",
"thunder wolf dragon of the end material",
"thunder wolf dragon of the upper material",
"thunder wolf dragon of Takeshi end material",
"gold Raikou end material",
"gold Raikou inscription scraps of",
"power dragon of the end material",
"power dragon of the upper material",
"power dragon of Takeshi end material",
"behemoth end material",
"behemoth top material",
"Takeshi end material of behemoth",
"Awakitsuneryu end material",
"Awakitsuneryu top material",
"Takeshi end material of Awakitsuneryu",
"Kiryu end material",
"Kiryu top material",
"Takeshi end material of Kiryu",
"燼滅 blade edge material",
"燼滅 blade inscription scraps of",
"TodorokiRyu end material",
"TodorokiRyu top material",
"Takeshi end material of TodorokiRyu",
"rough claw end material",
"inscription scraps of rough claw",
"thousand blade dragon of the end material",
"thousand blade dragon of the upper material",
"thousand blade dragon of Takeshi end material",
"black 蝕竜 end material",
"black 蝕竜 top material",
"Takeshi end material of black 蝕竜",
"heaven around the dragon of the end material",
"heaven around the dragon of the upper material",
"gold lion of the top material",
"gold lion of Takeshi end material",
"fear 暴竜 top material",
"fear 暴竜 Takeshi end material",
"giraffe end material",
"giraffe top material",
"steel dragon of the end material",
"steel dragon of the upper material",
"Chameleos of end material",
"Chameleos of the top material",
"flame king dragon of the end material",
"flame King Dragon of the top material",
"Haryu top material",
"Kuzureryu top material",
"煌黒 dragon of the upper material",
"ArashiRyu top material",
"Mukuro end material",
"Mukuro top material",
"Mukuro dragon of the upper material",
"ferocious end material",
"ferocious Motanzai",
"variant end material",
"variant of inscription end material",
"female fire of the dragon? ? ? ?",
"gold fire of the dragon? ? ? ?",
"Murasakidokuhime? ? ? ?",
"fire of the dragon? ? ? ? ?",
"silver fire of the dragon? ? ? ?",
"of Black Flame King? ? ? ?",
"boggy did? ?",
"Kaitori? ? ? ? ?",
"Dokukaitori? ? ? ?",
"water dragon? ? ? ? ?",
"of giraffe? ? ? ?",
"Dosuranposu?",
"Dosugeneposu?",
"Dosuiosu?",
"Dosugareosu?",
"of black wolf bird? ? ? ?",
"Sekigan? ? ? ? ?",
"Tatekani? ? ? ? ?",
"Hoko砕? ? ? ? ?",
"Kamakani? ? ? ? ?",
"snow lion? ? ? ?",
"gold lion? ? ? ?",
"incensed gold lion? ?",
"of steel dragon? ? ? ? ?",
"of Chameleos? ? ? ? ?",
"flame king of dragon? ? ? ?",
"Daiinoshishi? ? ? ? ?",
"TodorokiRyu? ? ? ? ?",
"rough claw? ? ? ?",
"Haryu? ? ? ? ?",
"of lava dragon? ? ? ?",
"迅竜? ? ? ? ?",
"white Gale? ? ? ?",
"Kuzureryu? ? ? ? ?",
"fear of 暴竜? ? ? ?",
"anger 喰恐 暴竜? ?",
"爆鎚 of the dragon? ? ? ?",
"Takaramatoi? ? ? ? ?",
"Kairyu of? ? ? ? ?",
"water beast? ? ? ? ?",
"flame halberd of the dragon? ? ? ?",
"煌黒 of a dragon? ? ? ?",
"Otsuchiryu? ? ? ?",
"latent port of the dragon? ? ? ?",
"Kaminariokamiryu? ? ? ?",
"gold Raikou? ? ? ?",
"ArashiRyu? ? ? ? ?",
"blue bear beast? ? ? ?",
"crimson helmet? ? ? ? ?",
"white rabbit beast? ? ? ?",
"heavy snow Lord? ? ? ?",
"red instep beast? ? ? ?",
"砕竜? ? ? ? ?",
"Kisarukitsune? ? ? ?",
"Onikaeru? ? ? ? ?",
"Iwa穿? ? ? ? ?",
"of garbled shark? ? ? ?",
"Shibohebiryu? ? ? ?",
"heavy beetle? ? ? ?",
"black 蝕竜? ? ? ?",
"heaven around the dragon? ? ? ?",
"Toru of beetle? ? ? ?",
"thousand blade of the dragon? ? ? ?",
"nocturnal bird? ? ? ? ?",
"Kiryu? ? ? ? ?",
"燼滅 blade? ? ? ?",
"power dragon? ? ? ? ?",
"Awakitsuneryu? ? ? ?",
"behemoth? ? ? ? ?",
"corpse of a dragon? ? ? ? ?",
"跳狗 of the dragon? ? ? ?",
"Aputonosu? ?",
"Apukerosu? ?",
"Kelvin? ? ? ?",
"Moss? ? ? ? ?",
"kantharos? ?",
"Langosta? ?",
"Ranposu? ? ?",
"Geneposu? ? ?",
"Eos? ? ?",
"sand dragon? ? ? ? ?",
"Fango? ? ?",
"Popo? ? ? ? ?",
"Gianosu? ? ?",
"Gaushika? ? ?",
"wings snake dragon? ? ? ?",
"Yaozami? ? ?",
"Gamizami? ? ?",
"Burango? ? ?",
"Rinopurosu? ?",
"of flying beetle? ? ? ?",
"of beetle? ? ? ? ?",
"of Jagyi? ? ?",
"Jagyinosu?",
"aquatic beast? ? ? ?",
"lava beast? ? ? ?",
"vertical skin of the dragon? ? ? ?",
"Gagua? ? ?",
"Sukuagiru? ?",
"shield insects? ? ? ? ?",
"Makkao? ? ?",
"neck ringing of the dragon? ? ? ?",
"Kumohitsujishika? ? ? ?",
"Akindonguri",
"large Akindonguri",
"super special training of teaching certificate",
"secret notes of the super special training",
"ancient varistor bullets",
"poison pearl [1]",
"poison Pearl [2]",
"耐麻 pearl [1]",
"耐麻 Pearl [2]",
"耐眠 pearl [1]",
"耐眠 Pearl [2]",
"anti-dielectric pearl [1]",
"Seizettama [1]",
"soundproof pearl [1]",
"soundproof Pearl [3]",
"Bofutama [1]",
"Bofutama [2]",
"seismic pearl [1]",
"KoShintama [1]",
"耐達 Migakutama [1]",
"anti-Dharma Tama [1]",
"heat tolerance pearl [1]",
"cold pearl [1]",
"Kitakazetama [1]",
"Minamikazetama [1]",
"耐盗 pearl [1]",
"耐防 pearl [1]",
"Kokyotama [1]",
"Kokyotama [3]",
"Kingakutama [1]",
"KinKiwamutama [1]",
"Kokizutama [1]",
"attack Pearl [1]",
"attack Pearl [2]",
"attack Pearl [3]",
"defense pearl [1]",
"defense Pearl [2]",
"physical fitness ball [1]",
"refractory pearl [1]",
"Seihitama [1]",
"water pearl [1]",
"Seisuitama [1]",
"lightning pearl [1]",
"Seikaminaritama [1]",
"ice class pearl [1]",
"Seikoritama [1]",
"耐龍 pearl [1]",
"Seiryutama [1]",
"genus 耐珠 [1]",
"genus 耐珠 [3]",
"flame ball [1]",
"flame ball [2]",
"running water pearl [1]",
"running water pearl [2]",
"lightning pearl [1]",
"lightning ball [2]",
"freezing pearl [1]",
"freezing Pearl [2]",
"broken Ryutama [1]",
"broken Ryutama [2]",
"ShokuOsamutama [1]",
"ShokuOsamutama [3]",
"suicide pearl [1]",
"suicide Pearl [2]",
"polishing ball [1]",
"Takumitama [2]",
"Takumitama [3]",
"Kitetsutama [1]",
"Kitetsutama [3]",
"swordsman pearl [1]",
"swordsman Pearl [3]",
"Tsuyoshiha pearl [1]",
"Tsuyoshiha Pearl [3]",
"blunt object pearl [1]",
"blunt object ball [2]",
"sword pearl [1]",
"sword Pearl [2]",
"抜打 pearl [1]",
"抜打 Pearl [3]",
"Hayaosametama [1]",
"Hayaosametama [2]",
"early Hamatama [1]",
"early Hamatama [2]",
"suppress anti-ball [1]",
"suppress anti-ball [3]",
"point Saitama [1]",
"strength bullets pearl [1]",
"strength bombs Pearl [3]",
"through ball [1]",
"through ball [3]",
"shotgun pearl [1]",
"shotgun Pearl [3]",
"Heavy bullet pearl [1]",
"Heavy bullet ball [3]",
"pressurized bombs Pearl [1]",
"pressurized bombs Pearl [2]",
"Kanukitama [1]",
"pressurized Chitama [1]",
"pressurized 榴珠 [1]",
"pressurized 拡珠 [1]",
"Dokubintama [1]",
"痺瓶 pearl [1]",
"痺瓶 Pearl [2]",
"Nemuribintama [1]",
"Tsuyobintama [1]",
"Tsuyobintama [2]",
"Shokubintama [1]",
"Shokubintama [2]",
"Sebbintama [1]",
"Genbintama [1]",
"爆瓶 pearl [1]",
"rapid fire ball [1]",
"rapid fire ball [3]",
"Ihotama [1]",
"Ihotama [2]",
"loaded ball [2]",
"loaded ball [3]",
"strange Saitama [1]",
"Fushidantama [1]",
"Fushidantama [2]",
"expert pearl [1]",
"master Pearl [2]",
"master Pearl [3]",
"crasher pearl [1]",
"crasher Pearl [3]",
"continuous 撃珠 [1]",
"continuous 撃珠 [3]",
"Special Account pearl [1]",
"Special Account Tama [2]",
"Shokukaitama [1]",
"Shokukaitama [2]",
"satisfaction pearl [1]",
"shortening pearl [1]",
"shortening Pearl [3]",
"strength Hashitama [1]",
"strength Hashitama [3]",
"body art pearl [1]",
"body art Tama [2]",
"Hayakitama [1]",
"Hayakitama [2]",
"avoidance pearl [1]",
"avoidance Pearl [2]",
"jump ball [1]",
"foam ball [1]",
"impregnable pearl [1]",
"impregnable Pearl [2]",
"Tsuyokabetama [1]",
"Tsuyokabetama [2]",
"KO pearl [1]",
"KO Pearl [2]",
"Datsukitama [1]",
"Datsukitama [2]",
"drum and fife pearl [1]",
"gunnery pearl [1]",
"heavy 撃珠 [1]",
"heavy 撃珠 [3]",
"爆師 pearl [1]",
"fully open pearl [1]",
"fully open ball [2]",
"Fighting Spirit pearl [1]",
"Fighting Spirit Pearl [2]",
"intact pearl [1]",
"intact pearl [2]",
"opportunity pearl [1]",
"underlying strength pearl [1]",
"underlying strength Pearl [2]",
"adversity pearl [1]",
"adversity Pearl [2]",
"frenzy pearl [1]",
"frenzy Pearl [2]",
"predicament pearl [1]",
"predicament Pearl [2]",
"guts pearl [1]",
"guts Pearl [2]",
"Shinobuashi pearl [1]",
"helm pearl [1]",
"name helm pearl [1]",
"word of command pearl [1]",
"word of command Pearl [2]",
"power 慣珠 [1]",
"Hien Pearl [1]",
"innocent pearl [1]",
"Chisato pearl [1]",
"observation pearl [1]",
"hunter pearl [1]",
"transportation pearl [1]",
"bless pearl [1]",
"Jingo pearl [1]",
"hero pearl [1]",
"hero Tama [3]",
"healing pearl [1]",
"healing Pearl [2]",
"Hayafukutama [1]",
"Hayafukutama [2]",
"duration pearl [1]",
"fraternity pearl [1]",
"fraternity Pearl [2]",
"Mushokutama [1]",
"ShokuKantama [1]",
"fast food pearl [1]",
"fast food Tama [3]",
"diet pearl [1]",
"carnivorous pearl [1]",
"meat good ball [1]",
"mushroom good ball [1]",
"wild grass pearl [1]",
"Dr. Pearl [1]",
"bullet made of pearl [1]",
"trap nurse Pearl [1]",
"collected pearl [1]",
"Mitsushutama [1]",
"Mitsuuranaitama [1]",
"Mamoru stone pearl [1]",
"blessing pearl [1]",
"fortune ball [1]",
"fortune ball [3]",
"peeling pearl [1]",
"stripping Pearl [3]",
"capture Tama [1]",
"capture Tama [3]",
"Rekisuzutama [1]",
"Hajimeryotama [1]",
"Yukihanatama [1]",
"Senyutama [1]",
"tomato juice",
"emblem of the fairy tail",
"pirate J cat gold coins",
"cardboard",
"Uniqlo coin",
"studio path",
"Gudegude and eggs",
"soul stone",
"Close coin",
"bicycle parts join the club notice",
"underground arena tickets",
"Gee's coin",
"Colo ticket",
"Ushio coin",
"Magikoin",
"Meiten stardust of",
"fate of the card",
"pirate J ticket",
"Famitsu ticket",
"Den Geki ticket",
"Uniqlo S coin",
"studio X path",
"studio G path",
"studio W path",
"salmon fillets",
"Macross Δ coin",
"wind of tact",
"Irwin boarding pass",
"Super Mushroom",
"Design Palette",
"Triforce",
"Samusukoin",
"goddess of look",
"embrace of the goddess",
"SF coin",
"Red Orb",
"Ceramica Le titanium",
"hero of testimony",
"baby diary",
"warm diary",
"Monster Hunter part letterzine",
"Monster Hunter section join the club notice",
"Monster Hunter part certification",
"Puppet ticket",
"Great Stone",
"postman's letter of",
"dummy 1",
"dummy 2",
"dummy 3",
"dummy 4",
"dummy 5",
"dummy 6",
"dummy 7",
"dummy 8",
"dummy 9",
"dummy 10",
"dummy 11",
"dummy 12",
"dummy 13",
"dummy 14",
"dummy 15",
"dummy 16",
"dummy 17",
"dummy 18",
"dummy 19",
"dummy 20"
        };
    }
}
